### ISSUE TITLE
Elaborate about the status of PRLib

### ISSUE THREAD

**Issue by wrznr** [ZaMaZaN4iK/PRLib#16]
After getting everything compiled, I played around with the binarization sample processors and the following image.
![test cropped](https://user-images.githubusercontent.com/26707219/66304672-0f725880-e8fe-11e9-9910-aa5c289ba54f.jpg)
The results I end up with are rather strange.
Wolf:
![test_wolf](https://user-images.githubusercontent.com/26707219/66304799-4f394000-e8fe-11e9-9dde-036ec5f5d3bb.jpg)
Sauvola:
![test_sauvola](https://user-images.githubusercontent.com/26707219/66304908-8b6ca080-e8fe-11e9-8f76-e5073f026d7f.jpg)
Feng:
![test_feng](https://user-images.githubusercontent.com/26707219/66304976-a50de800-e8fe-11e9-8e9a-814ed20ca27d.jpg)

and so on. Only `LocalOtsu` seems to work as expected. Could write a few words about the status of your implementation?

**Comment by ZaMaZaN4iK** [comment]
Oh... You are asking about very difficuly problems. There are no at least known for me problems with my implementations of binarizations.

The main problem is that you are trying to use binarizations with Global Threshold. What does it mean - we calculate one threshold for whole image depending on different stuff which can get from an image and then apply it. As you see it works not so good as we want. But an image can have areas with different brightness levels. And global binarizations are not suitable for it.

We can do better here and try to use local binarizations when we calculate threshold for every piece for image (we can tune granularity for the choice between speed and quality). And Local Otsu is one of the simplest local binarization.

I suggest to use local binarizations if you don't know enough information about input image.
