### ISSUE TITLE
windows10 & visual studio 2015 environment. 

### ISSUE THREAD

**Issue by yunhyejoung** [ZaMaZaN4iK/PRLib#17]
Hello~ 

1. I download at https://github.com/leha-bot/PRLib. 

2. I build https://github.com/leha-bot/PRLib File by CMake in windows10 & visual studio 2015 environment. 

![error12](https://user-images.githubusercontent.com/23716146/110366335-7b279a80-8089-11eb-808f-c66081f4d5d5.JPG)

3. I built the above file. However, the following compilation error occurred.
![error11](https://user-images.githubusercontent.com/23716146/110366432-a0b4a400-8089-11eb-9608-1f2ebd31f4a3.JPG)

How do I solve this problem?

Please reply.

**Comment by ZaMaZaN4iK** [comment]
Did you try to build this repo instead of leha-bot variant? I partially support only this repo, not leha-bot one.

So try to build this repo and if you still will have any issues - describe them here.

**Comment by yunhyejoung** [comment]
No one has uploaded a solution to this issue either.

**Comment by yunhyejoung** [comment]
No one has uploaded a solution to this issue either.
please help me...

**Comment by ZaMaZaN4iK** [comment]
Did you try to build an example with this repo instead of leha-bot? :)

**Comment by yunhyejoung** [comment]
yes.
I download https://github.com/ZaMaZaN4iK/PRLib

![error13](https://user-images.githubusercontent.com/23716146/110367985-c17df900-808b-11eb-866e-3cbc252a08e2.JPG)

**Comment by yunhyejoung** [comment]
yes.
I download https://github.com/ZaMaZaN4iK/PRLib
![Uploading error13.JPG…]()

**Comment by ZaMaZaN4iK** [comment]
Seems like you should somehow allow narrowing conversions in your compiler. I don't know exactly, which compiler flag does it, so I can't help you with it.

Another option is to try to manually fix all narrowing conversions in C++ way - PR is very welcome here (since I have no time to fix it)!

**Comment by yunhyejoung** [comment]
**I must use PRLib.

Please Help me. ㅠㅠㅠ please,,,,**

**Comment by yunhyejoung** [comment]
#include "getopt.h" ===> C1083 : 'getopt.h' : No such file or directory

what is error ?

**Comment by ZaMaZaN4iK** [comment]
This file is mistakenly included by me in one algorithm for layers extraction. I will disable that algorithm and move it to another directory.

**Comment by zamazan4ik** [comment]
Now it's fixed. Thanks for the report!
