### ISSUE TITLE
If there is a scratch between words and words, how do you get rid of the scratches?

### ISSUE THREAD

**Issue by yunhyejoung** [ZaMaZaN4iK/PRLib#18]
If there is a scratch between words and words, how do you get remove of the scratches? ====> OCR

**Comment by ZaMaZaN4iK** [comment]
Honestly, we have no good algorithms for doing such stuff here. Probably this file will help you a little bit: https://github.com/ZaMaZaN4iK/PRLib/blob/master/src/removeLines.cpp

**Comment by ZaMaZaN4iK** [comment]
No, this algorithm cannot remove such lines. You can try to use any other line detection algorithm. Not sure is there any suitable algorithm for such a task in PRLIB
