### ISSUE TITLE
Tesseract

### ISSUE THREAD

**Issue by yunhyejoung** [ZaMaZaN4iK/PRLib#19]
I use tesseract.

Can I use PRLib's Thinning algorithm by preprocessing of Tesseract ocr Lib ?

Can I use the Thinning algorithm with Tesseract preprocessing?

**Comment by ZaMaZaN4iK** [comment]
Yes, you can. That's exactly the original purpose of the library. WIth PRLIB you can write any preprocessing you want, and when run Tesseract over preprocessed image.

**Comment by ZaMaZaN4iK** [comment]
Yes, you can. That's exactly the original purpose of the library. WIth PRLIB you can write any preprocessing you want, and when run Tesseract over preprocessed image.

**Comment by nebiyebln** [comment]
can you tell me how to do this please?? @ZaMaZaN4iK

**Comment by zamazan4ik** [comment]
You run any preprocessing algorithm from PRLib on an image. Then preprocessed image you pass to Tesseract library.

**Comment by nebiyebln** [comment]
sorry but there is not enough explanation for this. I did the download, created a directory called build, ran the make command. how will I use it in my project later on. please tell me about it. @ZaMaZaN4iK

**Comment by zamazan4ik** [comment]
You should add PRLib to your new project (via copy-pasting sources and built files OR via CMake OR via any dependency manager - whatever you want). Then you need to manually read your image file into the memory, apply any of PRLib's algorithms according to your needs. Then resulting image you should pass to Tesseract. I don't remember exactly, which format shall be used with Tesseract, so you need to read Tesseract documentation first.
